// <auto-generated />
namespace UniShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addQuantityforproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addQuantityforproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201706101214499_add Quantity for product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
